### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by asharani97** [szzexpoi/attention_asd_screening#1]
I am getting the given error while running the code :

Start 28-fold validation for fold 1
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    main()
  File "main.py", line 131, in main
    acc = validation_loo(epoch)
  File "main.py", line 109, in validation_loo
    pred = model(img,fix)
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./model/model.py", line 98, in forward
    valid_len = self.process_lengths(fixation) # computing valid fixation lengths
  File "./model/model.py", line 80, in process_lengths
    lengths = list(max_length - input.data.eq(0).sum(1).squeeze())
  File "/DATA/rani.1/.local/lib/python3.7/site-packages/torch/tensor.py", line 430, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

**Comment by szzexpoi** [comment]
The error indicates that you are forcing a list on a scalar input. Are you using batch size 1 for the experiment?

**Comment by asharani97** [comment]
Solved
